image: 'maven:alpine'

cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test

build:
  stage: build
  script:
    - apk update && apk add openssl ca-certificates git
    - curl 'https://gist.githubusercontent.com/kg6zvp/4887a5d266f37d11853e78df35ad7c28/raw/3581075404ebaa42b7b7ef878ee08ed679ae2758/built-ttv4.sh'|bash -
    - mvn package -DskipTests
  artifacts:
    paths:
      - prod/target/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - mvn test

after_script:
  - echo "End CI"
